name: Build .NET MAUI App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Windows App
        run: dotnet publish YourMauiProject.csproj -c Release -f net8.0-windows10.0.19041.0 -o out/windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maui-windows
          path: out/windows

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore

      - name: Build macOS App
        run: dotnet publish YourMauiProject.csproj -c Release -f net8.0-macos -o out/macos

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maui-macos
          path: out/macos
